spring.rabbitmq.addresses=amqps://vhaqkhrr:nt2T5kl4SoCNcTpaUJ6rSKNBgHAZ_J9C@cow.rmq2.cloudamqp.com/vhaqkhrr
spring.rabbitmq.username=vhaqkhrr
spring.rabbitmq.password=nt2T5kl4SoCNcTpaUJ6rSKNBgHAZ_J9C
spring.rabbitmq.virtual-host=vhaqkhrr

# IMPORTANT pentru CloudAMQP (folose?te TLS!)
spring.rabbitmq.ssl.enabled=true
